// One flat config for the whole workspace. `pnpm lint` runs a single eslint pass from the
// repo root rather than a per-package script, because the per-package ones were fake: web's
// "next lint" hit an unconfigured-ESLint prompt, apps/api had no eslint binary at all, and
// both swallowed the failure with `|| echo lint-skip`, so CI linted zero files while green.
import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";
import nextPlugin from "@next/eslint-plugin-next";
import reactHooks from "eslint-plugin-react-hooks";

export default tseslint.config(
  {
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/.next/**",
      "**/target/**",
      "**/coverage/**",
      "apps/mobile/**",
      // Regenerated by `next build`; its triple-slash references are not ours to fix.
      "apps/web/next-env.d.ts",
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    languageOptions: {
      globals: { ...globals.node, ...globals.es2024 },
    },
    rules: {
      // Deliberate loosenings, not laziness - each one is noise on this codebase rather
      // than a defect signal. Tighten them as the code is cleaned up.
      //
      // Raw SQL rows and Prisma $queryRaw results are legitimately `any` here.
      "@typescript-eslint/no-explicit-any": "off",
      // The repo prefixes intentionally-unused params rather than deleting them.
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrors: "none" },
      ],
      // Back on. typescript-eslint's eslint-recommended disables the core rule for .ts files
      // on the assumption that tsc will catch it - which only holds for files a tsconfig
      // actually includes. apps/api/tsconfig.json only includes "src", so prisma/seed.ts was
      // covered by neither, and a duplicate "photo" key sat there silently killing every
      // per-dish photo. The rule reads ObjectExpression nodes, so TS interfaces and type
      // literals are unaffected and there is nothing to lose by having it on everywhere.
      "no-dupe-keys": "error",
    },
  },

  // Next.js app: browser globals plus the framework's own correctness rules.
  {
    files: ["apps/web/**/*.{ts,tsx,js,jsx}"],
    plugins: { "@next/next": nextPlugin, "react-hooks": reactHooks },
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
    },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs["core-web-vitals"].rules,
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",
      // App Router only - there is no pages/ directory, and the rule warns on stderr
      // about not finding one when eslint runs from the repo root.
      "@next/next/no-html-link-for-pages": "off",
    },
  },

  // Config files and scripts run in Node and are not part of the typed app code.
  {
    files: ["**/*.config.{js,mjs,ts}", "**/prisma/seed.ts"],
    languageOptions: { globals: globals.node },
  },
);
